"""create_strata_schema

Revision ID: 64ef3d4daafc
Revises: 
Create Date: 2026-09-24 12:05:13.574632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64ef3d4daafc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('dataset_name', sa.String(length=255), nullable=False),
    sa.Column('actor_name', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.String(length=64), nullable=False),
    sa.Column('badge_color', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_logs_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('audit_trail',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.String(length=64), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_trail', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_trail_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_trail_actor'), ['actor'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_trail_timestamp'), ['timestamp'], unique=False)

    op.create_table('branches',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('dataset_name', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('head_commit_id', sa.String(length=64), nullable=False),
    sa.Column('head_hash', sa.String(length=128), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('protected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ahead_count', sa.Integer(), nullable=False),
    sa.Column('behind_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_branches_dataset_name'), ['dataset_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_branches_name'), ['name'], unique=False)

    op.create_table('commits',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=16), nullable=False),
    sa.Column('full_hash', sa.String(length=128), nullable=False),
    sa.Column('dataset_name', sa.String(length=255), nullable=False),
    sa.Column('parent_hash', sa.String(length=128), nullable=True),
    sa.Column('version_tag', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=128), nullable=False),
    sa.Column('timestamp', sa.String(length=64), nullable=False),
    sa.Column('delta_rows', sa.String(length=64), nullable=False),
    sa.Column('delta_columns', sa.String(length=64), nullable=False),
    sa.Column('added_cols', sa.JSON(), nullable=False),
    sa.Column('removed_cols', sa.JSON(), nullable=False),
    sa.Column('modified_cols', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('access_level', sa.String(length=32), nullable=False),
    sa.Column('custom_metadata', sa.JSON(), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commits_dataset_name'), ['dataset_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_commits_full_hash'), ['full_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_commits_hash'), ['hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_commits_owner_id'), ['owner_id'], unique=False)

    op.create_table('dataset_comments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('dataset_id', sa.String(length=64), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=True),
    sa.Column('column_name', sa.String(length=128), nullable=True),
    sa.Column('author_name', sa.String(length=128), nullable=False),
    sa.Column('author_role', sa.String(length=64), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dataset_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataset_comments_dataset_id'), ['dataset_id'], unique=False)

    op.create_table('dataset_permissions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('dataset_id', sa.String(length=64), nullable=False),
    sa.Column('min_role', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dataset_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataset_permissions_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_permissions_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('datasets',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=True),
    sa.Column('workspace_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('format', sa.String(length=32), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('view_name', sa.String(length=128), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('total_columns', sa.Integer(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('latest_version', sa.String(length=32), nullable=False),
    sa.Column('version_count', sa.Integer(), nullable=False),
    sa.Column('schema_fields', sa.JSON(), nullable=False),
    sa.Column('preview_rows', sa.JSON(), nullable=False),
    sa.Column('sheets', sa.JSON(), nullable=True),
    sa.Column('active_sheet', sa.String(length=128), nullable=True),
    sa.Column('column_stats', sa.JSON(), nullable=False),
    sa.Column('pii_flags', sa.JSON(), nullable=False),
    sa.Column('full_quality', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_datasets_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_datasets_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_datasets_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_datasets_view_name'), ['view_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_datasets_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('dead_letter_jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('pipeline_id', sa.String(length=64), nullable=False),
    sa.Column('failed_at', sa.String(length=64), nullable=False),
    sa.Column('error_type', sa.String(length=128), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dead_letter_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dead_letter_jobs_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dead_letter_jobs_pipeline_id'), ['pipeline_id'], unique=False)

    op.create_table('integration_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('webhook_id', sa.String(length=64), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('integration_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integration_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_events_webhook_id'), ['webhook_id'], unique=False)

    op.create_table('ml_models',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('framework', sa.String(length=64), nullable=False),
    sa.Column('algorithm', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('dataset_name', sa.String(length=255), nullable=False),
    sa.Column('dataset_version_hash', sa.String(length=128), nullable=False),
    sa.Column('experiment_tracker', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=128), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('hyperparameters', sa.JSON(), nullable=False),
    sa.Column('artifact_uri', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ml_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_models_dataset_name'), ['dataset_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_models_dataset_version_hash'), ['dataset_version_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_models_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_models_owner_id'), ['owner_id'], unique=False)

    op.create_table('pipeline_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('pipeline_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.String(length=64), nullable=False),
    sa.Column('completed_at', sa.String(length=64), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('rows_processed', sa.Integer(), nullable=False),
    sa.Column('logs', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipeline_runs_pipeline_id'), ['pipeline_id'], unique=False)

    op.create_table('pipelines',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_dataset_id', sa.String(length=64), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('schedule', sa.String(length=64), nullable=False),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('max_memory_mb', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('last_run_at', sa.String(length=64), nullable=True),
    sa.Column('last_status', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pipelines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipelines_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipelines_target_dataset_id'), ['target_dataset_id'], unique=False)

    op.create_table('review_requests',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('dataset_name', sa.String(length=255), nullable=False),
    sa.Column('source_branch', sa.String(length=128), nullable=False),
    sa.Column('target_branch', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_requests_dataset_name'), ['dataset_name'], unique=False)

    op.create_table('showcase_items',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=128), nullable=False),
    sa.Column('author_avatar', sa.Text(), nullable=True),
    sa.Column('author_verified', sa.Boolean(), nullable=False),
    sa.Column('format', sa.String(length=32), nullable=False),
    sa.Column('license', sa.String(length=64), nullable=False),
    sa.Column('doi', sa.String(length=128), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('total_columns', sa.Integer(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('downloads', sa.Integer(), nullable=False),
    sa.Column('forks', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.String(length=64), nullable=False),
    sa.Column('schema_fields', sa.JSON(), nullable=False),
    sa.Column('sample_rows', sa.JSON(), nullable=False),
    sa.Column('sample_query', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('showcase_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_showcase_items_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_showcase_items_slug'), ['slug'], unique=False)

    op.create_table('user_favorites',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('dataset_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_favorites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_favorites_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_favorites_user_id'), ['user_id'], unique=False)

    op.create_table('user_recents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('dataset_id', sa.String(length=64), nullable=False),
    sa.Column('viewed_at', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_recents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_recents_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_recents_user_id'), ['user_id'], unique=False)

    op.create_table('user_starred_showcase',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('showcase_id', sa.String(length=64), nullable=False),
    sa.Column('starred_at', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_starred_showcase', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_starred_showcase_showcase_id'), ['showcase_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_starred_showcase_user_id'), ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('webhook_configs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('service', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspace_invitations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workspace_invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_invitations_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_invitations_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('workspace_members',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('joined_at', sa.String(length=64), nullable=False),
    sa.Column('avatar', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workspace_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_members_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_members_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_members_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('workspaces',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('plan', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspaces_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspaces_slug'), ['slug'], unique=False)

    op.create_table('dataset_versions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('dataset_id', sa.String(length=64), nullable=False),
    sa.Column('version_hash', sa.String(length=128), nullable=False),
    sa.Column('parent_version_hash', sa.String(length=128), nullable=True),
    sa.Column('version_tag', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('format', sa.String(length=32), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('column_count', sa.Integer(), nullable=False),
    sa.Column('schema_json', sa.JSON(), nullable=False),
    sa.Column('profile_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dataset_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataset_versions_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_versions_version_hash'), ['version_hash'], unique=False)

    op.create_table('share_links',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('dataset_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    with op.batch_alter_table('share_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_share_links_dataset_id'), ['dataset_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_share_links_dataset_id'))

    op.drop_table('share_links')
    with op.batch_alter_table('dataset_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataset_versions_version_hash'))
        batch_op.drop_index(batch_op.f('ix_dataset_versions_dataset_id'))

    op.drop_table('dataset_versions')
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspaces_slug'))
        batch_op.drop_index(batch_op.f('ix_workspaces_owner_id'))

    op.drop_table('workspaces')
    with op.batch_alter_table('workspace_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_members_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_workspace_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_workspace_members_email'))

    op.drop_table('workspace_members')
    with op.batch_alter_table('workspace_invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_invitations_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_workspace_invitations_email'))

    op.drop_table('workspace_invitations')
    op.drop_table('webhook_configs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('user_starred_showcase', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_starred_showcase_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_starred_showcase_showcase_id'))

    op.drop_table('user_starred_showcase')
    with op.batch_alter_table('user_recents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_recents_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_recents_dataset_id'))

    op.drop_table('user_recents')
    with op.batch_alter_table('user_favorites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_favorites_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_favorites_dataset_id'))

    op.drop_table('user_favorites')
    with op.batch_alter_table('showcase_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_showcase_items_slug'))
        batch_op.drop_index(batch_op.f('ix_showcase_items_domain'))

    op.drop_table('showcase_items')
    with op.batch_alter_table('review_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_requests_dataset_name'))

    op.drop_table('review_requests')
    with op.batch_alter_table('pipelines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipelines_target_dataset_id'))
        batch_op.drop_index(batch_op.f('ix_pipelines_owner_id'))

    op.drop_table('pipelines')
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_runs_pipeline_id'))

    op.drop_table('pipeline_runs')
    with op.batch_alter_table('ml_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_models_owner_id'))
        batch_op.drop_index(batch_op.f('ix_ml_models_name'))
        batch_op.drop_index(batch_op.f('ix_ml_models_dataset_version_hash'))
        batch_op.drop_index(batch_op.f('ix_ml_models_dataset_name'))

    op.drop_table('ml_models')
    with op.batch_alter_table('integration_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integration_events_webhook_id'))
        batch_op.drop_index(batch_op.f('ix_integration_events_event_type'))

    op.drop_table('integration_events')
    with op.batch_alter_table('dead_letter_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dead_letter_jobs_pipeline_id'))
        batch_op.drop_index(batch_op.f('ix_dead_letter_jobs_job_id'))

    op.drop_table('dead_letter_jobs')
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datasets_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_datasets_view_name'))
        batch_op.drop_index(batch_op.f('ix_datasets_owner_id'))
        batch_op.drop_index(batch_op.f('ix_datasets_name'))
        batch_op.drop_index(batch_op.f('ix_datasets_content_hash'))

    op.drop_table('datasets')
    with op.batch_alter_table('dataset_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataset_permissions_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_dataset_permissions_dataset_id'))

    op.drop_table('dataset_permissions')
    with op.batch_alter_table('dataset_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataset_comments_dataset_id'))

    op.drop_table('dataset_comments')
    with op.batch_alter_table('commits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commits_owner_id'))
        batch_op.drop_index(batch_op.f('ix_commits_hash'))
        batch_op.drop_index(batch_op.f('ix_commits_full_hash'))
        batch_op.drop_index(batch_op.f('ix_commits_dataset_name'))

    op.drop_table('commits')
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_branches_name'))
        batch_op.drop_index(batch_op.f('ix_branches_dataset_name'))

    op.drop_table('branches')
    with op.batch_alter_table('audit_trail', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_trail_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_trail_actor'))
        batch_op.drop_index(batch_op.f('ix_audit_trail_action'))

    op.drop_table('audit_trail')
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_logs_workspace_id'))

    op.drop_table('activity_logs')
    # ### end Alembic commands ###
